# Generated by Django 2.2.4 on 2019-11-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0002_auto_20191105_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yale',
            name='long_rate',
        ),
        migrations.RemoveField(
            model_name='yale',
            name='us_population',
        ),
    ]
