# Generated by Django 2.2.4 on 2019-12-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0005_auto_20191211_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='crude',
            name='frequency',
            field=models.DateField(null=True, unique=True),
        ),
    ]
