# Generated by Django 2.2.4 on 2019-12-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0006_crude_frequency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crude',
        ),
    ]
