# Generated by Django 2.2.4 on 2019-12-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0007_delete_crude'),
    ]

    operations = [
        migrations.CreateModel(
            name='crude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.DateField(null=True, unique=True)),
                ('wti_real_price', models.DecimalField(decimal_places=4, max_digits=7)),
                ('non_opec_liquid_fuels_production', models.DecimalField(decimal_places=4, max_digits=6)),
                ('saudi_arabia_crude_oil_production_change', models.DecimalField(decimal_places=4, max_digits=6)),
                ('opec_spare_production_capacity', models.DecimalField(decimal_places=4, max_digits=6)),
                ('non_oecd_liquid_fuels_consumption_change', models.DecimalField(decimal_places=4, max_digits=6)),
                ('non_oecd_gdp_growth', models.DecimalField(decimal_places=4, max_digits=6)),
                ('oecd_liquid_fuels_consumption_change', models.DecimalField(decimal_places=4, max_digits=6)),
                ('wti_crude_12_1_futures_price_spread_change', models.DecimalField(decimal_places=4, max_digits=6)),
                ('oecd_liquid_fuels_inventories_change', models.DecimalField(decimal_places=4, max_digits=7)),
                ('avg_num_outstanding_oil_futures_contract', models.DecimalField(decimal_places=4, max_digits=8)),
                ('assets_under_management', models.DecimalField(decimal_places=4, max_digits=7)),
                ('world_gdp_growth', models.DecimalField(decimal_places=4, max_digits=5)),
                ('world_liquid_fuels_consumption_change', models.DecimalField(decimal_places=4, max_digits=5)),
                ('dow_jones_ubs_commodity_index', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
