# Generated by Django 2.2.4 on 2019-12-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0010_auto_20191223_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crude',
            name='world_gdp_growth',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
