# Generated by Django 2.2.4 on 2020-01-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0013_timeseries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeseries',
            old_name='price',
            new_name='inx',
        ),
        migrations.RenameField(
            model_name='timeseries',
            old_name='frequency',
            new_name='observation_date',
        ),
    ]
