# Generated by Django 2.2.4 on 2020-04-07 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MachineLearning', '0016_arima_predictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='series_visited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_clicked', models.DateTimeField(auto_now=True)),
                ('series', models.CharField(max_length=100, verbose_name='Series Title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
