# Generated by Django 2.2.4 on 2020-04-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0017_series_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series_visited',
            name='date_time_clicked',
            field=models.DateTimeField(),
        ),
    ]
