# Generated by Django 2.2.4 on 2020-04-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0021_auto_20200418_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='econometric_coefficients',
            name='independent_variables',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='Independent Variable'),
        ),
    ]
