# Generated by Django 2.2.4 on 2020-05-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0022_econometric_coefficients_independent_variables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arima_predictions',
            name='series_title',
        ),
        migrations.CreateModel(
            name='arima_forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachineLearning.series_names', verbose_name='Series')),
            ],
        ),
        migrations.CreateModel(
            name='arima_coefficients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.CharField(db_index=True, max_length=10, null=True, verbose_name='Variable')),
                ('coefficients', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pvalues', models.DecimalField(decimal_places=4, max_digits=10)),
                ('forecasted_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MachineLearning.arima_forecast')),
            ],
        ),
        migrations.AddField(
            model_name='arima_predictions',
            name='forecasted_series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MachineLearning.arima_forecast'),
        ),
    ]
