# Generated by Django 2.2.4 on 2020-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineLearning', '0023_auto_20200512_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='econometric_predictions',
            name='lower_ci',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='econometric_predictions',
            name='upper_ci',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
